### ISSUE TITLE
Banco Inter permite compra de frações

### ISSUE THREAD

**Issue by yurighensev** [jmonteiro/comparaconta#13]
Tenho algumas ações pelo banco Inter, e vejo que ele permite sim compra de frações. Inclusive o padrão da plataforma é a compra de ações por valor da ordem (mínimo é $5), apesar de darem opções de compra por quantidade também.

https://github.com/jmonteiro/comparaconta/blob/653b6120787e110a6533a1d02161f4af4b901312/pages/corretoras_exterior/inter.yml#L71-L73

**Comment by jmonteiro** [comment]
Obrigado! Atualizado em https://github.com/jmonteiro/comparaconta/commit/f26945e31d8a08664426f873c7e384a17a0090c3
